### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by eng-khaled1** [HazyResearch/pdftotree#104]
**Describe the bug**
i'm trying to convert this [.pdf](https://github.com/HazyResearch/pdftotree/files/5471925/UACompanionSpecificationforIEC611313Model.pdf) to hOCR as follows

**To Reproduce**
```
import pdftotree

pdftotree.parse('/home/khaled/Desktop/extract/UACompanionSpecificationforIEC611313Model.pdf', html_path='/home/khaled/Desktop/extract/', visualize=False)
```
**but i'm getting the following output:**
**Error Logs/Screenshots**
`Traceback (most recent call last):
  File "/home/khaled/PycharmProjects/pdftotrees.py", line 21, i
    pdftotree.parse('/home/khaled/Desktop/extract/UACompanionSp
  File "/home/khaled/.local/lib/python3.8/site-packages/pdftotr
    pdf_tree = extractor.get_tree_structure(model_type, model)
  File "/home/khaled/.local/lib/python3.8/site-packages/pdftotr
    self.tree[page_num], ref_page_seen = parse_tree_structure(
  File "/home/khaled/.local/lib/python3.8/site-packages/pdftotr
    text_candidates, ref_page_seen = extract_text_candidates(
  File "/home/khaled/.local/lib/python3.8/site-packages/pdftotr
    round(cid2span[cid]["min_x"]) == round(cid2span[cid2]["min_
OverflowError: cannot convert float infinity to integer`
**with or without a training  model. and when trying to train a model using:** 
`extract_tables --train-pdf /home/khaled/Desktop/paleo/ml/train.pdf.list.paleo.not.scanned --gt-train /home/khaled/Desktop/paleo/ml/gt.train --test-pdf /home/khaled/Desktop/paleo/ml/test.pdf.list.paleo.not.scanned --gt-test /home/khaled/Desktop/paleo/ml/gt.test --datapath /home/khaled/Desktop/paleo/documents/ --model-path /home/khaled/Desktop/paleo/model.pkl`
**I'm getting the output** 
```
Traceback (most recent call last):
  File "/home/khaled/.local/bin/extract_tables", line 13, in <module>
    from pdftotree.ml.TableExtractML import TableExtractorML
  File "/home/khaled/.local/lib/python3.8/site-packages/pdftotree/ml/TableExtractML.py", line 21, in <module>
    from pdftotree.utils.pdf.pdf_utils import analyze_pages, normalize_pdf
ImportError: cannot import name 'analyze_pages' from 'pdftotree.utils.pdf.pdf_utils' (/home/khaled/.local/lib/python3.8/site-packages/pdftotree/utils/pdf/pdf_utils.py)
```

i would be very thankful if you could help me on this 

 

**Environment **
 - OS: Ubuntu 20.04
 - `pdftotree` v0.5.0
 - `pdfminer.six` Version: 20200726
 - `snorkel` 0.9.6

[training set.zip](https://github.com/HazyResearch/pdftotree/files/5471941/training.set.zip)
[UACompanionSpecificationforIEC611313ClientFBs.pdf](https://github.com/HazyResearch/pdftotree/files/5471943/UACompanionSpecificationforIEC611313ClientFBs.pdf)
[UACompanionSpecificationforIEC611313Model.pdf](https://github.com/HazyResearch/pdftotree/files/5471944/UACompanionSpecificationforIEC611313Model.pdf)
[model.zip](https://github.com/HazyResearch/pdftotree/files/5471945/model.zip)

**Comment by HiromuHota** [comment]
Thanks for reporting.
The OverflowError looks like a bug to me. Let me see what's happening.
The ImportError was also reported by #105. Since #105 reports ImportError only, I'll fix it at #105.
