### ISSUE TITLE
Native-digital PDFs reported as scanned

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/pdftotree#27]
This document is native-digital and should be able to be converted.
```
$ pdftotree -vv CentralSemiconductorCorp_2N4013.pdf 
[ERROR] pdftotree.core - Document is scanned, cannot build tree structure
HTML output to None
```

**Comment by clayms** [comment]
same issue with this document
https://www.theice.com/publicdocs/regulatory_filings/ICUS_Rules_Clean_up.pdf

**Comment by jlozano2** [comment]
i am also having the same issue trying to convert a pdf to html... i recieve the error: [ERROR] pdftotree.core - Document is scanned, cannot build tree structure. This pdf is unl to convert I have used Adober Reader, Nitro, and MS Word. Any suggestions for it to work ?

**Comment by HiromuHota** [comment]
Merging #71 made this issue irrelevant as pdftotree will greedily extract contents from PDF even if it looks scanned.
Another issue such as #72 happens as a side-effect, but this issue itself can be closed now.
