### ISSUE TITLE
authorization issues with wand library

### ISSUE THREAD

**Issue by Zhenshan-Jin** [HazyResearch/pdftotree#44]
**Describe the bug**
If I set the option `visualize = True`, there is always a complaint from the dependency wand library about authentication, 

**To Reproduce**
```
tree = pdftotree.parse(
    pdf_file,
    html_path=html_path,
    model_type="visual",
    model_path="../input/paleo_visual_model.h5",
    visualize=True
)
```

**Error Logs/Screenshots**
```
wand.exceptions.PolicyError: not authorized `/home/.../test_pdf/test1.pdf' @ error/constitute.c/ReadImage/412
Exception ignored in: <bound method Resource.__del__ of <wand.image.Image: (empty)>>
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/wand/resource.py", line 232, in __del__
  File ".../lib/python3.6/site-packages/wand/image.py", line 2767, in destroy
TypeError: object of type 'NoneType' has no len()
```

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - `pdftotree` Version: v0.4.0

**Additional context**

**Comment by lukehsiao** [comment]
This should be an issue with ImageMagick. See https://github.com/HazyResearch/fonduer/issues/170 for the workaround.

**Comment by Zhenshan-Jin** [comment]
thanks, @lukehsiao , it works!
