### ISSUE TITLE
pdftotree.parse() returns None

### ISSUE THREAD

**Issue by jay-reynolds** [HazyResearch/pdftotree#45]
**Describe the bug**
pdftotree.parse() returns None 

**To Reproduce**
1)
successful install on ubuntu 18.04 using:
sudo apt install python3-tk
pip install pdftotree

2) 
import pdftotree
pdf_file = 'mypdf.pdf'
output = pdftotree.parse(pdf_file, html_path=None, model_type=None, model_path=None, favor_figures=True, visualize=False)

returns None type in output.

Had the exact same problem in Windows, decide to setup an unbuntu machine to give it a try, same results.  I've tried various .pdf files as well, to no avail.

What should I check for to debug this?   

Thank you kindly in advance, -J

**Comment by jay-reynolds** [comment]
Update:  my apologies, I wasn't thorough enough in testing various .pdf documents, as the docs I have are all scanned and OCR'd, as it turns out.

When I tested a .pdf of purely digital origin (grabbed one from pubmed), pdftotree worked as expected.

However, I'd still love to try it on my data.  Any advice would be greatly appreciated.

**Comment by lukehsiao** [comment]
We currently do not support scanned documents, unfortunately. Though, it is something we'd like to do in the future. We'd recommend trying Adobe or Abby to convert your documents if they are scanned.
