### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by ayoyu** [HazyResearch/pdftotree#47]
Hi, I'm using pdftotree on Ubuntu with python3.6. I first installed python3 toolkit, then pdftotree. So when I import pdftotree, this error appeared
ModuleNotFoundError: No module named 'chardet'
So I think I should install chardet but I want to know which version should I install to be in sync with the application. Thank you for your feedback

**Comment by ayoyu** [comment]
Hey guys, this problem is provided by pdfminer on the utils script and exactly this part:
if six.PY3:
    import chardet  # For str encoding detection in Py3
    unicode = str
so, i installed chardet==3.0.4 and the problem is solved.

**Comment by lukehsiao** [comment]
Thanks!

**Comment by lukehsiao** [comment]
https://github.com/pdfminer/pdfminer.six/issues/213
