### ISSUE TITLE
pdftotree returns very long untraceable html code.

### ISSUE THREAD

**Issue by mrmammadov** [HazyResearch/pdftotree#48]
Hello. I am on Linux Ubuntu 18.04 LTS machine and trying to convert pdf files to html files for feeding into Fonduer Data Model. But when I am running pdftotree in Jupyter Notebook, it return a long , hashed HTML like file which is impossible to understand and save and work with. 
See the attached file

![screenshot from 2018-12-13 19-37-59](https://user-images.githubusercontent.com/19167079/49959940-3abf2d80-ff0f-11e8-85c3-86f4e068eaa7.png)

**Comment by lukehsiao** [comment]
Fonduer does not yet support `pdftotree` output. As you noticed above, `pdftotree` does **not** convert a PDF into HTML. Instead, it converts PDF into an HTML-like structure. The numbers you are noticing above are bounding box information from the PDF, and is the expected output of `pdftotree`.
