### ISSUE TITLE
ModuleNotFoundError: No module named 'pdftotree.ml'; 'pdftotree' is not a package

### ISSUE THREAD

**Issue by dzhang228** [HazyResearch/pdftotree#51]
Hi,

I installed the pdftotree, and tried the extract_tables.py. Got a ModuleNotFoundError, saying pdftotree is not a package. Details of the commend line input and output are listed below, please advice. Thanks
```
py extract_tables.py --train-pdf data/paleo/ml/train.pdf.list.paleo.not.scanned --gt-train data/paleo/ml/gt.train --test-pdf data/paleo/ml/test.pdf.list.paleo.not.scanned --gt-test data/paleo/ml/gt.test --datapath data/paleo/documents/ --model-path data/model.pkl
Traceback (most recent call last):
  File "extract_tables.py", line 13, in <module>
    from pdftotree.ml.TableExtractML import TableExtractorML
ModuleNotFoundError: No module named 'pdftotree.ml'; 'pdftotree' is not a package
```

**Comment by dzhang228** [comment]
problem is solved.

**Comment by Ruthvicp** [comment]
@dzhang228 - Can you share the steps in fixing it ? May I know how long it took for training a model

**Comment by rageshS** [comment]
@dzhang228 - How did you solve this error? Why did you close the thred in a short notice ?

**Comment by rageshS** [comment]
I think @dzhang228, not an active user.
