### ISSUE TITLE
Any Pre-trained model available to download

### ISSUE THREAD

**Issue by Ruthvicp** [HazyResearch/pdftotree#52]
I really like the work here. But when I convert pdf to HTML it takes about 2-3min for each pdf as I do not have a pre-trained model. I did try to create one but my windows machine freezes every time I do it. It would be nice if you make the pre-trained model available.

**Comment by imaurer** [comment]
I downloaded this to a data/paleo subdirectory:
http://i.stanford.edu/hazy/share/fonduer/pdftotree_paleo.tar.gz

And ran this:
extract_tables --train-pdf data/paleo/ml/train.pdf.list.paleo.not.scanned --gt-train data/paleo/ml/gt.train --test-pdf data/paleo/ml/test.pdf.list.paleo.not.scanned --gt-test data/paleo/ml/gt.test --datapath data/paleo/documents/ --model-path data/model.pkl

And got this file (gzip'd) after about 45 minutes:
[model.pkl.gz](https://github.com/HazyResearch/pdftotree/files/3203106/model.pkl.gz)

Needs to be unzipped. I then ran it on one of the files:
pdftotree -mt ml -m ./data/model.pkl -o result data/paleo/documents/CLAIRE_et_al-2006-Geobiology.pdf

Didn't extract the 1 table to HTML as I was hoping. It didn't seem to handle "rowspans" for me. But still a promising project...

**Comment by Ruthvicp** [comment]
Yup, I did the same and got the model file (.pkl) after an hour. While the model was training there was nothing on the console and for a moment I actually thought my computer froze, but eventually found few statements on the console. Just a thought for developers that it would be nice to print some statements (with progress) while the model is training.

**Comment by HiromuHota** [comment]
A pre-trained model exists at `tests/input/paleo_model.pkl` in the repository. This is an answer to the original question.
