### ISSUE TITLE
pdftotree.parse() returns None

### ISSUE THREAD

**Issue by gtholpadiperitusai** [HazyResearch/pdftotree#54]
**Describe the bug**
A call to `html = pdftotree.parse()` returns `None` for some documents.

**To Reproduce**
1. Download the file 
[CaseStudy_ACS.pdf](https://github.com/HazyResearch/pdftotree/files/3088229/CaseStudy_ACS.pdf)

2. Execute the code
`html = pdftotree.parse(pdf_file="CaseStudy_ACS.pdf", html_path=None, model_type=None, model_path=None, favor_figures=True, visualize=False)`

**Expected behavior**
The variable `html` should contain the html markup for the text in the PDF.

**Error Logs/Screenshots**
However the variable `html` is set to None.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
- Python: 3.6.4 (Anaconda distribution)
 - `pdftotree` Version: v0.4.0

**Comment by BoPengGit** [comment]
https://github.com/HazyResearch/pdftotree/issues/45

?

**Comment by gtholpadiperitusai** [comment]
Thanks for the pointer @BoPengGit . I checked the example I have shared above. It is not a [scanned document](https://www.lightenpdf.com/knowledge-base/scanned-pdf-ocr.html). I am able to select the text. Also, on zooming, the fonts do not get blurred.

**Comment by Reyhaneh-Gh** [comment]
Hello,

I have the same issue. The issue in my case is that the parser returns None if the pdf (not scanned) file has a digital signature.
