### ISSUE TITLE
how to use the pdftotree command line

### ISSUE THREAD

**Issue by littletree123** [HazyResearch/pdftotree#57]
i have installed the pdftotree and its version is 0.4.0, i can import pdftotree in python , but cannot use the command line " pdftotree [optional] file_path " in cmd, meanwhile in python ,pdftotree.parse() returns nothing, how to use it?

my environment:
 windows10
 python 3.7.4
 pdftotree 0.4.0

**Comment by HiromuHota** [comment]
It would be too late to ask the @littletree123 for details, but I think

> pdftotree.parse() returns nothing

means that your pdf looked a scanned one to pdftotree.
