### ISSUE TITLE
Does train Extract_tables take in pixel or points ?  

### ISSUE THREAD

**Issue by parzival1l** [HazyResearch/pdftotree#60]
Hi , can anyone please help me in figuring out what input format does extract_tables take in , is it in pixles or points and also how does it read that information, top->down  or bottom->up way. I have my custom labelled dataset and I wanna know this for training a model of my own, can anyone please help me with this.  @lukehsiao @SenWu

**Comment by HiromuHota** [comment]
@parzival1l As long as (top, left, bottom, right) and (page_width, page_height) are on the same scale, technically it doesn't matter.

As stated in README,
> Labels take the form of semicolon-separated tuples containing the values (page_num, page_width, page_height, top, left, bottom, right).

and (top, left, bottom, right) will be scaled by the given page_width and page_height (see the following code snippet).

https://github.com/HazyResearch/pdftotree/blob/67c37d1cccb873c65e3154e71170d2bc4e7c0132/pdftotree/ml/TableExtractML.py#L232-L240

Just for the record, the ground-truth for the paleo example (http://i.stanford.edu/hazy/share/fonduer/pdftotree_paleo.tar.gz) seems to have normalized the page_height to make it 951. This is probably to fit the page height with the screen height for annotations.
