### ISSUE TITLE
Read PDF files from HDFS

### ISSUE THREAD

**Issue by ashleo25** [HazyResearch/pdftotree#90]
Hi @stephenbach @mgoo @SenWu @vincentschen @ZZWENG 

I would like read my pdf files from hdfs and convert to html store back in html
So i would like to know how that can be achieved using pdftotree
Appreciate your help as this is something urgent i am looking into

**Comment by ashleo25** [comment]
Thanks @HiromuHota 
Same applies to fonduer . Can fonduer parse html files in hdfs or we need to have it locally and process 
My use case was that i have my pdf files in HDFS and i wanted to first convert them to html and store in HDFS 
These HTML files in hdfs are given to fonduer for parsing and generate the data model 
Is there any way integrate it with spark so that distributed processing can be used 
Appreciate your inputs 
@stephenbach @SenWu @mgoo @ashleo25

**Comment by lukehsiao** [comment]
@ashleo25, please do not tag a list of people for each of your messages. It breaks common GitHub etiquette, since you're tagging people who are not directly involved and generating spam for them.

**Comment by ashleo25** [comment]
@lukehsiao Sure i will take care. Sorry for the inconvenience

**Comment by lukehsiao** [comment]
>  Same applies to fonduer ?? Can fonduer parse html files in hdfs or we need to have it locally and process

Yes, the same applies to Fonduer. It's currently built to read from your local filesystem and doesn't integrate with Spark or other distributed processes systems at the moment.
